Updated quickstart and architecture
Music-Bot-for-Jitsi/Jimmi pull request #140
Opened 2022-03-31 20:26 UTC by antonplagemann

2022-03-31 20:29 UTC, p-fruck requested changes

2022-03-31 20:29 UTC, p-fruck commented on docs/ARCHITECTURE.md
> +[Trex](https://deno.land/x/trex) is a package management tool for Deno similar to NPM but keeping close to the Deno philosophy. Packages are cached and only one `import_map.json` file is generated. *
```suggestion
[Trex](https://deno.land/x/trex) is a package management tool for Deno similar to NPM but keeping close to the Deno philosophy. Packages are cached and only one `import_map.json` file is generated. **Update:** As deno has implemented its own task runner with `v1.20.1` we have removed Trex as dependency.
```

2022-03-31 20:29 UTC, piuswalter commented on docs/QUICKSTART.md
> +Inside the backend folder copy and rename `.env.example` to `.env` and fill in your desired settings.
```suggestion
Inside the `backend` folder copy and rename `.env.example` to `.env` and fill in your desired settings.
```

2022-03-31 22:01 UTC, piuswalter approved these changes

2022-04-01 06:06 UTC, p-fruck approved these changes

2022-04-01 06:07 UTC, merged